# Generated by Django 5.0.14 on 2026-07-02 00:27

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('collation', 'Collation Phase'), ('closed', 'Closed (Final Published)')], default='upcoming', max_length=15)),
                ('blockchain_contract_address', models.CharField(blank=True, max_length=64, null=True)),
                ('signatures', models.JSONField(blank=True, default=list, help_text='Tracks multi-sig signatures before closing')),
            ],
        ),
        migrations.CreateModel(
            name='NIMCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin', models.CharField(max_length=11, unique=True, verbose_name='NIN')),
                ('full_name', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100, verbose_name='LGA')),
                ('biometric_hash', models.TextField(help_text='Encrypted baseline for bimodal BVAS matching')),
            ],
            options={
                'verbose_name': 'NIMC Record',
                'verbose_name_plural': 'NIMC Records',
            },
        ),
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ward', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('registered_voters_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ElectoralUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=11, unique=True, verbose_name='NIN')),
                ('staff_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Staff ID')),
                ('vnin', models.CharField(blank=True, max_length=16, null=True, verbose_name='Virtual NIN')),
                ('role', models.CharField(choices=[('prospective', 'Prospective Voter'), ('voter', 'Registered Voter'), ('po', 'Presiding Officer (PO)'), ('apo', 'Assistant Presiding Officer (APO)'), ('spo', 'Supervisory Presiding Officer (SPO)'), ('co', 'Collation Officer (CO)'), ('ro', 'Returning Officer (RO)'), ('agent', 'Polling / Party Agent'), ('media', 'Accredited Media / Journalist'), ('observer', 'Election Observer'), ('auditor', 'Cybersecurity Auditor')], default='prospective', max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100, verbose_name='LGA')),
                ('is_verified', models.BooleanField(default=False)),
                ('passed_bimodal_auth', models.BooleanField(default=False, help_text='Facial/Fingerprint verified at BVAS')),
                ('needs_assistance', models.BooleanField(default=False, help_text='Flags profile as Assisted Voter')),
                ('ui_configuration', models.JSONField(default=dict, help_text='Stores TTS or high-contrast preferences')),
                ('language', models.CharField(default='English', help_text='Preferred interface/voice language', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('assigned_polling_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pollingunit')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('party', models.CharField(max_length=150)),
                ('party_abbr', models.CharField(max_length=20)),
                ('color', models.CharField(default='#1565c0', max_length=10)),
                ('manifesto', models.TextField()),
                ('running_mate', models.CharField(blank=True, max_length=150, null=True)),
                ('votes_count', models.PositiveIntegerField(default=0)),
                ('legal_affidavit_url', models.URLField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='api.election')),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('signup', 'Signup Verification'), ('reset', 'Password Reset'), ('ballot_auth', 'Ballot Cast Authorization')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisputeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('polling_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pollingunit')),
            ],
        ),
        migrations.CreateModel(
            name='ResultSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanned_form_url', models.URLField(help_text='Link to IReV portal document')),
                ('accredited_voters', models.PositiveIntegerField()),
                ('total_votes_cast', models.PositiveIntegerField()),
                ('po_digital_signature', models.CharField(max_length=256)),
                ('is_countersigned_by_agents', models.BooleanField(default=False)),
                ('flagged_for_overvoting', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.election')),
                ('polling_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pollingunit')),
                ('presiding_officer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='submitted_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('cryptographic_receipt', models.CharField(blank=True, help_text='Hash proving interaction with smart contract', max_length=256)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_records', to='api.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('voter', 'election')},
            },
        ),
    ]
