# Generated by Django 5.0.14 on 2026-07-02 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='signatures',
        ),
        migrations.CreateModel(
            name='AccreditationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('applicant_type', models.CharField(choices=[('media', 'Media House / Broadcaster'), ('observer', 'Domestic Observer (CSO)'), ('intl_observer', 'International Observer')], max_length=20)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', models.CharField(max_length=20)),
                ('organization_id', models.CharField(help_text='CAC number, press card ID, or international body reference', max_length=100)),
                ('mandate_description', models.TextField(help_text='Brief description of coverage/oversight mandate')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_accreditations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('invited_email', models.EmailField(max_length=254)),
                ('staff_number', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('po', 'Presiding Officer (PO)'), ('apo', 'Assistant Presiding Officer (APO)'), ('spo', 'Supervisory Presiding Officer (SPO)'), ('co', 'Collation Officer (CO)'), ('ro', 'Returning Officer (RO)'), ('auditor', 'Cybersecurity Auditor')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('assigned_polling_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pollingunit')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionClosureApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('digital_signature', models.CharField(max_length=256)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_approvals', to='api.election')),
            ],
            options={
                'unique_together': {('election', 'approved_by')},
            },
        ),
    ]
