# Generated by Django 5.0.14 on 2026-07-02 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_election_signatures_accreditationapplication_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='election',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='election',
            name='description',
            field=models.TextField(blank=True, help_text='Official INEC description of this election/ballot'),
        ),
        migrations.AddField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('presidential', 'Presidential'), ('gubernatorial', 'Gubernatorial'), ('senatorial', 'Senatorial'), ('house_reps', 'House of Representatives'), ('state_assembly', 'State House of Assembly'), ('council', 'Local Government / Council')], default='presidential', max_length=30, verbose_name='Election Type'),
        ),
        migrations.AddField(
            model_name='election',
            name='eligible_states',
            field=models.JSONField(default=list, help_text='List of state names eligible to participate. Empty = nationwide.'),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted (Internal)'), ('upcoming', 'Upcoming (Published)'), ('active', 'Active (Polls Open)'), ('collation', 'Collation Phase'), ('closed', 'Closed (Final Published)')], default='drafted', max_length=15),
        ),
        migrations.AlterField(
            model_name='electoraluser',
            name='role',
            field=models.CharField(choices=[('prospective', 'Prospective Voter'), ('voter', 'Registered Voter'), ('commissioner', 'INEC Electoral Commissioner'), ('po', 'Presiding Officer (PO)'), ('apo', 'Assistant Presiding Officer (APO)'), ('spo', 'Supervisory Presiding Officer (SPO)'), ('co', 'Collation Officer (CO)'), ('ro', 'Returning Officer (RO)'), ('agent', 'Polling / Party Agent'), ('media', 'Accredited Media / Journalist'), ('observer', 'Election Observer'), ('auditor', 'Cybersecurity Auditor')], default='prospective', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffinvitation',
            name='role',
            field=models.CharField(choices=[('commissioner', 'INEC Electoral Commissioner'), ('po', 'Presiding Officer (PO)'), ('apo', 'Assistant Presiding Officer (APO)'), ('spo', 'Supervisory Presiding Officer (SPO)'), ('co', 'Collation Officer (CO)'), ('ro', 'Returning Officer (RO)'), ('auditor', 'Cybersecurity Auditor')], max_length=20),
        ),
    ]
