# Generated by Django 5.0.14 on 2026-07-02 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_election_options_election_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingunit',
            name='collation_officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'co'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pu_as_co', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='presiding_officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'po'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pu_as_po', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='electoraluser',
            name='role',
            field=models.CharField(choices=[('prospective', 'Prospective Voter'), ('voter', 'Registered Voter'), ('commissioner', 'INEC Electoral Commissioner'), ('secretary', 'INEC Secretary'), ('po', 'Presiding Officer (PO)'), ('apo', 'Assistant Presiding Officer (APO)'), ('spo', 'Supervisory Presiding Officer (SPO)'), ('co', 'Collation Officer (CO)'), ('ro', 'Returning Officer (RO)'), ('agent', 'Polling / Party Agent'), ('media', 'Accredited Media / Journalist'), ('observer', 'Election Observer'), ('auditor', 'Cybersecurity Auditor')], default='prospective', max_length=20),
        ),
        migrations.AlterField(
            model_name='resultsheet',
            name='polling_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pollingunit'),
        ),
        migrations.AlterField(
            model_name='staffinvitation',
            name='role',
            field=models.CharField(choices=[('commissioner', 'INEC Electoral Commissioner'), ('secretary', 'INEC Secretary'), ('po', 'Presiding Officer (PO)'), ('apo', 'Assistant Presiding Officer (APO)'), ('spo', 'Supervisory Presiding Officer (SPO)'), ('co', 'Collation Officer (CO)'), ('ro', 'Returning Officer (RO)'), ('auditor', 'Cybersecurity Auditor')], max_length=20),
        ),
    ]
