# Generated by Django 5.0.14 on 2026-07-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_provision_secretary'),
    ]

    operations = [
        migrations.AddField(
            model_name='electoraluser',
            name='voter_id',
            field=models.CharField(blank=True, max_length=19, null=True, unique=True, verbose_name='Voter Identification Number (VIN)'),
        ),
    ]
