# Generated by Django 5.0.14 on 2026-07-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_electoraluser_voter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='electoraluser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
