# Generated by Django 5.0.14 on 2026-07-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_electoraluser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='end_time',
            field=models.TimeField(default='14:30:00'),
        ),
        migrations.AddField(
            model_name='election',
            name='start_time',
            field=models.TimeField(default='08:30:00'),
        ),
    ]
