# Generated by Django 5.0.14 on 2026-07-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_election_end_time_election_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electoraluser',
            name='vnin',
        ),
        migrations.AlterField(
            model_name='electoraluser',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='electoraluser',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='electoraluser',
            name='lga',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='LGA'),
        ),
        migrations.AlterField(
            model_name='electoraluser',
            name='passed_bimodal_auth',
            field=models.BooleanField(default=True, help_text='Facial/Fingerprint verified at BVAS'),
        ),
        migrations.AlterField(
            model_name='electoraluser',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='VoterRegistrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrn', models.CharField(help_text='Alphanumeric VRN printed on the back of the PVC (Permanent Voter Card)', max_length=20, unique=True, verbose_name='Voter Registration Number')),
                ('nin', models.CharField(db_index=True, max_length=11, verbose_name='NIN')),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('polling_unit_code', models.CharField(blank=True, help_text='Code of the polling unit where voter physically registered', max_length=50)),
                ('is_claimed', models.BooleanField(default=False, help_text='Set to True when voter completes online account creation')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Voter Registration Record',
                'verbose_name_plural': 'Voter Registration Records',
                'indexes': [models.Index(fields=['vrn', 'nin'], name='api_voterre_vrn_2ff8cf_idx')],
            },
        ),
    ]
