# Generated by Django 5.0.14 on 2026-07-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_election_end_time_election_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electoraluser',
            old_name='staff_number',
            new_name='staff_id',
        ),
        migrations.RenameField(
            model_name='staffinvitation',
            old_name='staff_number',
            new_name='staff_id',
        ),
    ]
