# Generated by Django 5.0.14 on 2026-07-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_staff_number_electoraluser_staff_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electoraluser',
            old_name='staff_id',
            new_name='staff_number',
        ),
    ]
