# Generated by Django 6.0.7 on 2026-07-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_voter_registration_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electoraluser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
