# Generated by Django 6.0.7 on 2026-07-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_electoraluser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party_logo',
            field=models.ImageField(blank=True, null=True, upload_to='party_logos/'),
        ),
    ]
