# Generated by Django 5.0.14 on 2026-07-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_staff_id_electoraluser_staff_number'),
        ('api', '0011_candidate_party_logo'),
    ]

    operations = [
    ]
