# Generated by Django 5.0.14 on 2026-07-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20260709_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffinvitation',
            old_name='staff_id',
            new_name='staff_number',
        ),
        migrations.AlterField(
            model_name='electoraluser',
            name='staff_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Staff Number'),
        ),
    ]
